### ISSUE TITLE
add docker for development

### ISSUE THREAD

**Issue by donnyroufs** [donnyroufs/leaguedex#90]
When done look into implementing it for hosting. Which means we have to refactor the current workflow and vps.

**Comment by mmcxii** [comment]
I can't necessarily speak for using Docker as a dev environment, but as for using it to deploy I can be helpful. The only real hard part with your stack is the few extra lines needed to generate your Prisma files in the container.

**Comment by donnyroufs** [comment]
Yeah I figured something like that. Right now my git workflows are a mess, turning it into a dockerized app would make everything way easier to deploy as far as I'm aware. Haven't had the motivation to figure it all out yet though ;/ Since it will also require some downtime and potential data loss. @mmcxii

**Comment by mmcxii** [comment]
I can confirm Dockerized apps are very easy to deploy since everything is nicely contained within the, well, container. You can just set up a script on your hosting server (I use Digital Ocean) and have it pull your image and redeploy it. I'll try and figure out a Dockerfile today and you can use it whenever you're ready.

Side question, do you run your migrations automatically or manually? If automatically when do you do so?
